"""add_user_profile_fields

Revision ID: 3fc9f5948121
Revises: 96c9700a2224
Create Date: 2026-05-15 02:03:59.078224
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc9f5948121'
down_revision: Union[str, None] = '96c9700a2224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('interest_tags', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('season_level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('best_streak', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_correct_answers', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_questions_answered', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'total_questions_answered')
    op.drop_column('users', 'total_correct_answers')
    op.drop_column('users', 'best_streak')
    op.drop_column('users', 'total_score')
    op.drop_column('users', 'season_level')
    op.drop_column('users', 'interest_tags')
    op.drop_column('users', 'auth_provider_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
