"""daily_cosmetics_phase4a

Revision ID: 7e1cd8845037
Revises: 91a2ce59327d
Create Date: 2026-06-11 00:07:04.970815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1cd8845037'
down_revision: Union[str, None] = '91a2ce59327d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cosmetics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cosmetic_id', sa.String(length=50), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cosmetic_id', name='uq_user_cosmetic')
    )
    op.create_index(op.f('ix_user_cosmetics_cosmetic_id'), 'user_cosmetics', ['cosmetic_id'], unique=False)
    op.create_index(op.f('ix_user_cosmetics_user_id'), 'user_cosmetics', ['user_id'], unique=False)
    op.add_column('users', sa.Column('daily_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_daily_claim_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('equipped_frame', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('equipped_name_color', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('equipped_effect', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'equipped_effect')
    op.drop_column('users', 'equipped_name_color')
    op.drop_column('users', 'equipped_frame')
    op.drop_column('users', 'last_daily_claim_at')
    op.drop_column('users', 'daily_streak')
    op.drop_index(op.f('ix_user_cosmetics_user_id'), table_name='user_cosmetics')
    op.drop_index(op.f('ix_user_cosmetics_cosmetic_id'), table_name='user_cosmetics')
    op.drop_table('user_cosmetics')
    # ### end Alembic commands ###
