"""initial_schema

Revision ID: 96c9700a2224
Revises: 
Create Date: 2026-05-15 01:53:09.097925
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c9700a2224'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('DOGRU_YANLIS', 'GORSEL', 'KARSILASTIRMA', 'COKTAN_SECMELI', 'TAHMIN', name='question_type'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('round_suitability', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='approval_status'), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('correct_rate', sa.Float(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('real_answer', sa.Float(), nullable=True),
    sa.Column('scale', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_approval_status'), 'questions', ['approval_status'], unique=False)
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_id', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=140), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('favorite_category', sa.String(length=50), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user1_id', sa.UUID(), nullable=False),
    sa.Column('user2_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('TANIDIK', 'DOST', 'SIKI_DOST', 'YOLDAS', name='friendship_level'), nullable=False),
    sa.Column('games_together', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_user1_id'), 'friendships', ['user1_id'], unique=False)
    op.create_index(op.f('ix_friendships_user2_id'), 'friendships', ['user2_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('bot_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='game_status'), nullable=False),
    sa.Column('lobby_code', sa.String(length=10), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_code')
    )
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.Enum('AVATAR', 'FRAME', 'EFFECT', 'EMOTE', 'BADGE', name='item_type'), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_user_id'), 'inventory', ['user_id'], unique=False)
    op.create_table('leaderboard_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_user_date')
    )
    op.create_index(op.f('ix_leaderboard_daily_date'), 'leaderboard_daily', ['date'], unique=False)
    op.create_index(op.f('ix_leaderboard_daily_user_id'), 'leaderboard_daily', ['user_id'], unique=False)
    op.create_table('leaderboard_seasonal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', name='uq_seasonal_user_season')
    )
    op.create_index(op.f('ix_leaderboard_seasonal_season_id'), 'leaderboard_seasonal', ['season_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_seasonal_user_id'), 'leaderboard_seasonal', ['user_id'], unique=False)
    op.create_table('leaderboard_weekly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_user_week')
    )
    op.create_index(op.f('ix_leaderboard_weekly_user_id'), 'leaderboard_weekly', ['user_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_weekly_week_start'), 'leaderboard_weekly', ['week_start'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'REWARD', 'SPEND', name='transaction_type'), nullable=False),
    sa.Column('currency', sa.Enum('COIN', 'GEM', 'REAL', name='currency_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('game_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('bot_name', sa.String(length=30), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('final_round', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminated_at_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=20), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('answer_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_history_question_id'), 'question_history', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_history_user_id'), 'question_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_history_user_id'), table_name='question_history')
    op.drop_index(op.f('ix_question_history_question_id'), table_name='question_history')
    op.drop_table('question_history')
    op.drop_table('game_participants')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_leaderboard_weekly_week_start'), table_name='leaderboard_weekly')
    op.drop_index(op.f('ix_leaderboard_weekly_user_id'), table_name='leaderboard_weekly')
    op.drop_table('leaderboard_weekly')
    op.drop_index(op.f('ix_leaderboard_seasonal_user_id'), table_name='leaderboard_seasonal')
    op.drop_index(op.f('ix_leaderboard_seasonal_season_id'), table_name='leaderboard_seasonal')
    op.drop_table('leaderboard_seasonal')
    op.drop_index(op.f('ix_leaderboard_daily_user_id'), table_name='leaderboard_daily')
    op.drop_index(op.f('ix_leaderboard_daily_date'), table_name='leaderboard_daily')
    op.drop_table('leaderboard_daily')
    op.drop_index(op.f('ix_inventory_user_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('games')
    op.drop_index(op.f('ix_friendships_user2_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user1_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_index(op.f('ix_questions_approval_status'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
