"""season_battlepass

Revision ID: fa97faf7bee4
Revises: 7e1cd8845037
Create Date: 2026-06-11 01:37:02.020357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa97faf7bee4'
down_revision: Union[str, None] = '7e1cd8845037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('season_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('season_tier', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('has_battle_pass', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('season_claimed_free', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('season_claimed_premium', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'season_claimed_premium')
    op.drop_column('users', 'season_claimed_free')
    op.drop_column('users', 'has_battle_pass')
    op.drop_column('users', 'season_tier')
    op.drop_column('users', 'season_points')
    # ### end Alembic commands ###
